version: '3'
services:
  minecraft:
    container_name: mc_server
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports: 
      - '25565:25565'
      - '24454:24454/udp'
      - '8123:8123'
    environment: 
      EULA: 'TRUE'
      DIFFICULTY: 'normal'
      MOTD: 'Welcome to 1.17'

      # Version Settings
      VERSION: '1.17'

      # Settings
      SNOOPER_ENABLED: 0
      SPAWN_PROTECTION: 0

      # Admins
      OPS: 'cybericecream'
      
      # Player Settings
      MAX_PLAYERS: 20

      # Server Config
      MEMORY: '4G'
    volumes:
      - ./data:/data